site_name: "BLIS Online"

edit_uri: edit/main/docs/
repo_url: https://github.com/blisonline/blisonline.github.io

theme:
  name: material
  custom_dir: overrides  
  palette:
    primary: deep orange
    accent: black    
